name: Premier workflow

on:
  push:

jobs:
  premier_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: ls
        run: ls -l
        
      - name: shell script
        run: |
          chmod +x cowsay.sh
          ./cowsay.sh
          

