name: Premier workflow

on:
  push:

jobs:
  premier_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Message, ls et cat 
        run: |
          echo "Hello World"
          ls
          cat README.md

      - name: installation de cowsay
        run: sudo apt install cowsay -y

      - name: utilisation de cowsay
        run: cowsay -f dragon "Run for cover, I am a Dragon..." >> dragon.txt

      - name: vérification du fichier 
        run: grep -i "dragon" dragon.txt

      - name: lecture du fichier 
        run: cat dragon.txt
